version: '3.3'

services:
  mariadb:
    container_name: l2Ice-server-mariadb
    image: yobasystems/alpine-mariadb:latest
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  l2jserver:
    container_name: l2Ice-server-docker
    image: l2jserver/l2j-server-docker:latest
    restart: always
    environment:
      IP_ADDRESS: "127.0.0.1"
      LAN_ADDRESS: "10.0.0.0"
      LAN_SUBNET: "10.0.0.0/8"
      JAVA_XMS: "512m"
      JAVA_XMX: "2g" 
      RATE_XP: "1"
      RATE_SP: "1"
      QUEST_MULTIPLIER_XP: "1"
      QUEST_MULTIPLIER_SP: "1"
      QUEST_MULTIPLIER_REWARD: "1"
      AUTO_LEARN_SKILLS: "False"
      MAX_FREIGHT_SLOTS: "200"
      DWARF_RECIPE_LIMIT: "50"
      COMM_RECIPE_LIMIT: "50"
      CRAFTING_SPEED_MULTIPLIER: "1"
      FREE_TELEPORTING: "False"
      STARTING_ADENA: "0"
      STARTING_LEVEL: "1"
      STARTING_SP: "0"
      ALLOW_MANOR: "True"
      MAX_ONLINE_USERS: "500"
      MAX_WAREHOUSE_SLOTS_DWARF: "120"
      MAX_WAREHOUSE_SLOTS_NO_DWARF: "100"
      MAX_WAREHOUSE_SLOTS_CLAN: "200"
      PET_XP_RATE: "1"
      RATE_ADENA: "1"
      ADMIN_RIGHTS: "True"
      FORCE_GEODATA: "False"
      COORD_SYNC: "-1"
      HELLBOUND_ACCESS: "True"
      WEIGHT_LIMIT: "1"
      TVT_ENABLED: "True"
      SAVE_GM_SPAWN_ON_CUSTOM: "True"
      CUSTOM_SPAWNLIST_TABLE: "True"
      CUSTOM_NPC_DATA: "True"
      CUSTOM_TELEPORT_TABLE: "True"
      CUSTOM_NPC_BUFFER_TABLES: "True"
      CUSTOM_SKILLS_LOAD: "True"
      CUSTOM_ITEMS_LOAD: "True"
      CUSTOM_MULTISELL_LOAD: "True"
      CUSTOM_BUYLIST_LOAD: "True"
      VITALITY_SYSTEM: "True"
      ITEM_SPOIL_MULTIPLIER: "1"
      ITEM_DROP_MULTIPLIER: "1"
    depends_on:
      - mariadb
    ports:
      - "7777:7777"
      - "2106:2106"
